<?php

return [
  'banner' => [
    'image' => 'Sign up free',
    'subtitle' => 'Bitthrem is a young company that arises from the experience acquired over the years in the field of cryptocurrencies.<br><br>Focusing on various productive sectors. We have been established for 2 years and we work with private investors.',
    'title' => 'About us?',
  ],

  'function' => [
    'content' => '<strong>Wallet 1:</strong> The function of this wallet is to receive all the investments of our clients, the funds received are used by our team of professionals in order to generate benefits for the members.<br><br><strong>Wallet 2:</strong> It is responsible for creating a unique and individual Wallet for our clients in order to have full control of their funds. When the first Wallet sends the funds generated by our team, this 2nd is in charge of depositing the (ROI) of the profits to each of the wallets created (this balance will be reflected in your Main Balance).<br><br><strong><i>Invested funds are returned at the end of the stipulated time of the active plan.</i></strong>',
    'image' => 'Function Image',
    'subtitle' => 'Our system was developed layer by layer with the highest security filter. We have 2 shared Wallets.',
    'title' => 'System Function',
  ],

  'icons' => [
    'first' => 'Transparency',
    'second' => 'Cooperation',
    'third' => 'Synergy',
  ],

  'mission' => [
    'content' => 'Contribute to the success of our clients in the financial goals that they wish to fulfill with the investment plans that we offer them within the term and expected benefit, marketing and professionally and responsibly managing the investors portfolio of funds.',
    'title' => 'Our Mission',
  ],

  'vision' => [
    'content' => 'Reach the sight of many more people to become one of the best investment companies in the world, innovate in other areas of investment, open offices in different countries, expand our mining farms, etc. We want to continue being the best in the financial market and continue offering opportunities to all those who want to.',
    'title' => 'Our Vision',
  ]
];
